Hw2
calmsen/loadingparcels pull request #2
Opened 2024-12-24 06:26 UTC by calmsen

Сделал рефакторинг. Добавил два алгоритма и количество машин. Сделал сохранение в json. Добавил тесты.

2024-12-24 19:24 UTC, vbnz34343434 requested changes
Хорошая работа, по правкам только мелочи. 

Много где есть неформатированный код - можешь выставить в окне коммита нажав на шестеренку Reformat Code, Rearrange Code, если вдруг забываешь нажимать Ctrl+Alt+Shift+L

2024-12-24 19:24 UTC, vbnz34343434 commented on build.gradle.kts
> +    implementation("ch.qos.logback:logback-classic:1.4.12")
идея подсвечивает, что в этой версии зависимости есть уязвимости, на это нужно обращать внимание и не добавлять в актуальный проект такие версии

2024-12-24 19:24 UTC, vbnz34343434 commented on src/main/java/ru/calmsen/loadingparcels/Main.java
> +        var trucksMapper = new TrucksMapperImpl();
вот тут не совсем правильно пользуешься мапстрактом. У тебя же до компиляции нет этого класса и поэтому, у меня например, класс подчеркивается красным. Посмотри вот здесь как это делается на чистой джаве - https://mapstruct.org/documentation/stable/reference/html/#mappers-factory

2024-12-24 19:24 UTC, vbnz34343434 commented on src/main/java/ru/calmsen/loadingparcels/command/CommandContext.java
>  public class CommandContext {
очень клевый получился парсер команд, отличный интерфейс, удобно использовать. Мне прям очень нравится

2024-12-24 19:24 UTC, vbnz34343434 commented on src/main/java/ru/calmsen/loadingparcels/model/domain/enums/ViewFormat.java
> +        catch(Exception e){
код не отформатирован

2024-12-24 19:24 UTC, vbnz34343434 commented on src/main/java/ru/calmsen/loadingparcels/mapper/TrucksMapper.java
> +@Mapper
на самом деле оч круто что нашел мапстракт, оч удобная тема, пользуйся почаще)

2024-12-24 19:24 UTC, vbnz34343434 commented on src/main/java/ru/calmsen/loadingparcels/util/FileOutputDataWriter.java
> +    private final String fileName;
этот класс, если бы не имел этого поля, вполне себе мог бы быть в единственном экземпляре в приложении, а сейчас заставляет его создавать каждый раз

2024-12-24 19:24 UTC, vbnz34343434 commented on src/main/java/ru/calmsen/loadingparcels/util/JsonUtil.java
> +    public static  <T> T fromJson(String json, Class<T> classOfT) throws JsonSyntaxException{
1. `throws` тут не нужен, это unchecked исключение
2. если честно не уверен что этот класс, который просто проксит Gson, вообще нужен.

2024-12-25 04:55 UTC, calmsen commented on src/main/java/ru/calmsen/loadingparcels/util/JsonUtil.java
> +    public static  <T> T fromJson(String json, Class<T> classOfT) throws JsonSyntaxException{
1. Убрал
2. Вынес в утилитарный класс, чтобы иметь возможность изменить реализацию. Понятно, что методы статические, но все же так все равно есть какая-та абстракция. Плюс удобно вызывать просто один метод, чем создавать объекты для работы с json

2024-12-25 05:25 UTC, calmsen commented on src/main/java/ru/calmsen/loadingparcels/util/FileOutputDataWriter.java
> +    private final String fileName;
Да. Такая задумка и была. Это просто обертка над FileWriter. 
![image](https://github.com/user-attachments/assets/4fbdcf0d-3ce3-4f6f-b673-252ca6fb912e)

2024-12-25 05:29 UTC, calmsen commented on src/main/java/ru/calmsen/loadingparcels/util/FileOutputDataWriter.java
> +    private final String fileName;
К тому же мне нужна была реализация абстракции void write(String data). Которая может выводить данные в консоль, в файл и еще куда. Например на удаленный сервер.

2024-12-25 05:29 UTC, calmsen commented on build.gradle.kts
> +    implementation("ch.qos.logback:logback-classic:1.4.12")
Исправил

2024-12-25 05:30 UTC, calmsen commented on src/main/java/ru/calmsen/loadingparcels/Main.java
> +        var trucksMapper = new TrucksMapperImpl();
Исправил

2024-12-25 05:30 UTC, calmsen commented on src/main/java/ru/calmsen/loadingparcels/command/CommandContext.java
>  public class CommandContext {
Спасибо

2024-12-25 05:30 UTC, calmsen commented on src/main/java/ru/calmsen/loadingparcels/model/domain/enums/ViewFormat.java
> +        catch(Exception e){
Исправил

2024-12-25 19:34 UTC, vbnz34343434 approved these changes
Принято, можешь мерджить. На последние два коммента ревью посмотри, но к правкам необязательны

2024-12-25 19:34 UTC, vbnz34343434 commented on src/main/java/ru/calmsen/loadingparcels/Main.java
> +        var trucksMapper = Mappers.getMapper(TrucksMapper.class);
на самом деле в таком случае, этот маппер необязательно в сервисы прокидывать, класс-то получился статическим

2024-12-25 19:34 UTC, vbnz34343434 commented on src/main/java/ru/calmsen/loadingparcels/util/FileOutputDataWriter.java
> +    private final String fileName;
ну в целом в этом нет ничего страшного, ну будет создаваться лишний класс ну и ладно. Но при переносе приложения на spring возможно будут не очень прикольные моменты с этим, но это проблема нас в будущем)

2024-12-26 03:59 UTC, calmsen commented on src/main/java/ru/calmsen/loadingparcels/util/FileOutputDataWriter.java
> +    private final String fileName;
Данный класс создается через фабрику. А фабрика является синглтоном. Думаю не должно быть проблем.

2024-12-26 04:00 UTC, calmsen commented on src/main/java/ru/calmsen/loadingparcels/Main.java
> +        var trucksMapper = Mappers.getMapper(TrucksMapper.class);
А почему статический класс?
![image](https://github.com/user-attachments/assets/ad651e74-6650-47b6-9245-0cebaa43d0eb)

Или ты что-то другое имеешь ввиду?

2024-12-26 04:03 UTC, merged

2024-12-26 18:20 UTC, vbnz34343434 commented on src/main/java/ru/calmsen/loadingparcels/util/FileOutputDataWriter.java
> +    private final String fileName;
я к тому что в любом случае каждый класс-сервис у тебя будет бином и этот не сможет быть синглтоном, а придется его делать как prototype

2024-12-26 18:24 UTC, vbnz34343434 commented on src/main/java/ru/calmsen/loadingparcels/Main.java
> +        var trucksMapper = Mappers.getMapper(TrucksMapper.class);
ну не сам класс статичный, конечно, а именно доступ к его реализации. И я имею ввиду что тебе не надо его каждый раз создавать через `new ...`, а "статично" получить инстанс реализации интерфейса через `Mappers.getMapper(TrucksMapper.class).map(...)`